### ISSUE TITLE
registerApp returns "Device Token Unavailable" on Android

### ISSUE THREAD

**Issue by shamilovtim** [oracle/pushiomanager-react-native#10]
Followed the directions on the site and still receive this error message on Android. Can you confirm that you've followed your own setup directions in a fresh project, reading directly off of the docs on the website and can make the package work?

I receive the following two errors:
In native: `E/pushio: PIOGCMRIS oHI Error initializing FCM: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.`

and also on the JS side: "Device Token Unavailable" 

I also noticed that line 4 here in the docs looks suspiciously like a typo. 
<img width="965" alt="Screen Shot 2021-05-28 at 4 25 40 PM" src="https://user-images.githubusercontent.com/3495974/120038517-6942fd00-bfd1-11eb-95bb-ee292cc55ca8.png">

Our env:

deps:
```
"@react-native-firebase/app": "^11.2.0",
"@react-native-firebase/perf": "^11.2.0",
```

firebase BoM is close to `26.0.0`
which is messaging `21.0.0` and core `18.0.0`

**Comment by neerhaj** [comment]
Please try with `firebase-messaging` version 21.1.0.

If you still see the error message, please paste the full device logs from Logcat.

**Comment by shamilovtim** [comment]
I did use messaging from the 21.0 BoM and I did post the logcat logs. Before we go any further than this can you confirm that: 
1. You've validated and confirmed that this wrapper works with tract native firebase
2. You've validated and confirmed that this wrapper works with recent firebase BoMs?

**Comment by neerhaj** [comment]
BoM version 21.0 maps to `firebase-messaging` 19.0.1. 
In your first comment you said the BoM version is close to 26.0.0 which maps to messaging 21.0.0.

Confirm which version of BoM and firebase-messaging is your app using.

One-liner logs are not helpful in understanding the context of the error. We will need the full logs.

**Comment by shamilovtim** [comment]
@neerhaj The first post was accurate, the second one was confusion on my part. I didn't see that you were requesting a minor version bump (21.1.0 vs. 21.0.0). I just tried with the following:

```
                    android : [
                            minSdk    : 21,
                            targetSdk : 30,
                            compileSdk: 30,
                            buildTools: "30.0.0"
                    ],
                    firebase: [
                            bom           : "27.0.0"
                    ],
 ```
and  `"@react-native-firebase/app": "11.5.0",`
 which resolves to `firebase-messaging: 21.1.0` like you requested. Same error.
 
 I recorded the logs from this session: https://gist.github.com/shamilovtim/add611df3bb61d1edf351449c21c9c54

**Comment by shamilovtim** [comment]
Any comment about line 4 of the docs in my original post above? Is that a typo?

**Comment by neerhaj** [comment]
> Any comment about line 4 of the docs in my original post above? Is that a typo?

No, that is not a typo.

**Comment by shamilovtim** [comment]
This is resolved. The fix was deprecating half of our google play gradle dependencies, and bumping the rest. We also brought in the following dependency according to a bulletin that the SDK team forwarded to us:
`implementation 'com.google.android.gms:play-services-base:16.1.0' `
