### ISSUE TITLE
PushIOManager SDK has runtime errors with recent Firebase BoMs

### ISSUE THREAD

**Issue by shamilovtim** [oracle/pushiomanager-react-native#12]
`getInstance().getToken()` have been deprecated from sub modules of firebase. The token must now be obtained from the FirebaseInstallations SDK.

**Comment by neerhaj** [comment]
We are unable to address issues related to the SDK here. For SDK related issues, please raise a support request at https://support.oracle.com/. You may also contact your Oracle CX representative for help with raising the request.
