### ISSUE TITLE
On iOS Error/Success callbacks never reached in registerForAllRemoteNotificationTypes()

### ISSUE THREAD

**Issue by shamilovtim** [oracle/pushiomanager-react-native#13]
When calling `PushIOManager.registerForAllRemoteNotificationTypes((error, success) => {})` on iOS neither error nor success callback are ever reached. The native code does show an error log which is the following. Last message shows the specific native error 

```
default	10:58:50.804481-0400	Shipt	[PushIOManager] -[PushIOManager isReadytoTrackEvent:] SDK not configured, trackEvent ignored.
default	10:58:50.935326-0400	Shipt	[PushIOManager] -[PushIOManager isReadytoTrackEvent:] SDK not configured, trackEvent ignored.
default	10:58:50.945250-0400	Shipt	[PushIOManager] -[PIOConfigConfigurator sdkConfiguredCorrectlyFor:accountToken:conversionUrl:riAppId:accountName:apiHost:globalRoutingURL:] globalRoutingURL is nil.
default	10:58:50.950407-0400	Shipt	[PushIOManager] -[PIOEventManager getBatchEvents:] Events cannot be fetched, because batch is nil.
default	10:58:50.950752-0400	Shipt	[PushIOManager] -[PIOBatchRequestManager sendBatchWithCompletionHandler:] Unable to create URL or request parameters for batch.
default	10:58:50.951443-0400	Shipt	[PushIOManager] -[PIOEventManager getBatchEvents:] Events cannot be fetched, because batch is nil.
default	10:58:50.951714-0400	Shipt	[PushIOManager] -[PIOBatchRequestManager sendBatchWithCompletionHandler:] Unable to create URL or request parameters for batch.
default	10:58:50.952656-0400	Shipt	[PushIOManager] -[PIOEventManager getBatchEvents:] Events cannot be fetched, because batch is nil.
default	10:58:50.953095-0400	Shipt	[PushIOManager] -[PIOBatchRequestManager sendBatchWithCompletionHandler:] Unable to create URL or request parameters for batch.
default	10:58:50.956223-0400	Shipt	[PushIOManager] Calling UIApplication registerForRemoteNotifications to obtain the device token.
default	10:58:51.150329-0400	Shipt	[PushIOManager] Registration scheduled after setting userID value.
default	10:58:51.271009-0400	Shipt	Config - error: (null) response {"pushio":{"appName":"censored","platformName":"censored","platform_type":"ios","apiKey":"censored","apiHost":"api.pushio.com","bundleId":"censored","accountToken":"censored","conversionUrl":"censored","riAppId":"censored"}}
```

**Comment by s-wasan** [comment]
@shamilovtim You must be running the App in Simulator.
Please verify in the Xcode/App logs you will see this error:
[PushIOManager] -[PushIOManager didFailToRegisterForRemoteNotificationsWithError:] Failed to get device token. Error: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}

Please run the App in device. Remote Push Notifications does not support Simulator.

**Comment by shamilovtim** [comment]
@s-wasan It was run on-device on an iPhone 12. I provided the full logs off of that device and as you can see, the native error callback you've mentioned was never hit. I don't have the power to reopen this issue and as a matter of Github etiquette I don't think it should have been closed without you knowing that I was on a simulator.

**Comment by s-wasan** [comment]
@shamilovtim Its unclear from logs what is happening. We need more information to debug this. Could you create a sample hello world app and share with us. We need to verify your setup.

**Comment by shamilovtim** [comment]
> @shamilovtim Its unclear from logs what is happening. We need more information to debug this. Could you create a sample hello world app and share with us. We need to verify your setup.

I've asked a couple of times and would appreciate an answer. Do you know of any users who use this react native plugin successfully in production?

**Comment by shamilovtim** [comment]
Resolved, do not call `configureWithFileName:configName` in the native iOS code. Also use only some parts of the iOS docs to setup the RN app but which parts need to be manually clarified by Oracle

**Comment by joaovtpereira** [comment]
@shamilovtim could you demonstrate which parts of the documentation you included, I'm having trouble integrating with IOS?

**Comment by AndriySikora** [comment]
To fix the current issue, it is necessary to run the app on a real device that should connect to the wi-fi or cellular network.
