### ISSUE TITLE
Patch for hot reload redbox iOS bug

### ISSUE THREAD

**Issue by shamilovtim** [oracle/pushiomanager-react-native#14]
Hello,

I was wondering if the patch for the hot reload redbox iOS bug could be pushed up to a branch so we can adopt this code in our app. We're finding the iOS native workaround to be insufficient for our needs.

Thank you!

**Comment by shamilovtim** [comment]
@s-wasan any ETA on providing this?

**Comment by s-wasan** [comment]
@shamilovtim  
We are working on it and we are preparing the hotfix for these issues . Currently, release is under testing.
Both android and iOS fix will be available in upcoming hotfix release.
Thanks

**Comment by shamilovtim** [comment]
> @shamilovtim
> We are working on it and we are preparing the hotfix for these issues . Currently, release is under testing.
> Both android and iOS fix will be available in upcoming hotfix release.
> Thanks

@s-wasan Do you have a timeline for this hotfix? We're running out of time to keep waiting over here

**Comment by neerhaj** [comment]
Fix for the iOS issue is now available.
