### ISSUE TITLE
Error when run on iOS and why do you need to edit node_modules from iOS?

### ISSUE THREAD

**Issue by diegotsi** [oracle/pushiomanager-react-native#20]
First of all, I want to say congrats for creating an official bridge to React Native, I'm co creator of the [react-native-responsys](https://github.com/juntossomosmais/react-native-responsys).

I'm trying to implement this bridge on iOS but I'm getting the following error:

<img width="676" alt="Screen Shot 2021-07-12 at 18 29 31" src="https://user-images.githubusercontent.com/11574033/125358333-2188f280-e33f-11eb-8ac4-d2487d09d0a4.png">

It's the same problem with issue #5 I think it's a problem with the framework path, this step is very confusing in the documentation. 

Why do you need to edit the node_modules and put the framework there? this folder is regenerated every time we install a dependency, I create a bridge recently to another SDK and the framework is on the bridge. we don't need to care about this on our apps, I think makes sense we make the same approach to this lib. 

The same thing about android setup, maybe the `.aar` file can be inside this bridge.

**Comment by diegotsi** [comment]
#5

**Comment by s-wasan** [comment]
@diegotsi 
Could you please verify `PushIOManager.framework exist` at `../node_modules/react-native-pushiomanager/PushIOManager/` 

Also please run `pod install` after changing the `Podfile`.

**Comment by diegotsi** [comment]
Hi @s-wasan, thanks, but no, it's not working, same error with the `PushIOManager.framework at ../node_modules/react-native-pushiomanager/PushIOManager`.

Even it works I think that is not the best approach, the `node_modules` folder is regenerated every time on CI tool, first of all, I think we can eliminate the PushIoManager folder inside this lib, we just need one pod spec. With one podspec we don't need to edit our Podfile to put this line `../node_modules/react-native-pushiomanager/PushIOManager/` .

To avoid copying the `PushIOManager.framework` to the node_modules we can put it inside this bridge, maybe inside `ios/libs/folder`, and then edit the  **react-native-pushiomanager.podspec** to something like this:

```ruby
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-pushiomanager"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = "https://github.com/oracle/pushiomanager-react-native"
  s.license      = "UPL-1.0"
  # s.license    = { :type => "UPL-1.0", :file => "FILE_LICENSE" }
  s.authors      = { "Responsys" => "support@oracle.com" }
  s.platforms    = { :ios => "10.0" }
  s.source       = { :git => "https://github.com/oracle/pushiomanager-react-native.git", :tag => "#{s.version}" }

  s.source_files = "ios/**/*.{h,m,swift}"
  s.requires_arc = true

  s.vendored_frameworks = "ios/libs/PushIOManager.framework"
  s.preserve_paths = "ios/libs/PushIOManager.framework"

  s.libraries      = 'sqlite3'
  s.frameworks              = 'UserNotifications', 'CoreLocation', 'Foundation', 'UIKit'
  s.ios.frameworks          = 'WebKit'

  s.dependency "React"
end
```

With this, we don't need to edit our Podfile e don't need to edit the  node_modules to put the framework there.

That's the approach most of the bridges to react-native does, what do you think? I already tested it and it's working, can i open a Pull Request?

**Comment by marcioc0sta** [comment]
Nice job @diegotsi. Lets make it happen @s-wasan!

**Comment by JulioCVaz** [comment]
@diegotsi Nice job!

**Comment by s-wasan** [comment]
The reason we can not copy `PushIOManager.frameowrk` in this repository is because license of both of them are different. We currently don't have the approvals. Thats the reason we require this manual process.

This make sense.

@diegotsi  Will this Pod will be fetched and automatically installed by React on `pod install` considering `PushIOManager.framework` available at `ios/libs/PushIOManager.framework`?
