### ISSUE TITLE
No visible @interface for 'PushIOManager' declares the selector 'setDelayRegistration:'

### ISSUE THREAD

**Issue by duuhleon** [oracle/pushiomanager-react-native#22]
After i update for new version v6.48.3, i have this problem, and cannot build anymore my app, what can i do for this?

No visible @interface for 'PushIOManager' declares the selector 'setDelayRegistration:'

![image](https://user-images.githubusercontent.com/7553123/129748718-cc3c6693-5936-4c0e-861c-9dd5ffe68cda.png)

**Comment by neerhaj** [comment]
Please make sure that you update the native SDK framework as well. This plugin release is compatible with [iOS SDK v6.48.1](https://www.oracle.com/downloads/applications/cx/responsys-mobile-sdk.html).

**Comment by duuhleon** [comment]
> Please make sure that you update the native SDK framework as well. This plugin release is compatible with [iOS SDK v6.48.1](https://www.oracle.com/downloads/applications/cx/responsys-mobile-sdk.html).

That's it! if i use a 6.49 still having trouble, but if i use 6.48.1, it's works! thank you!
