### ISSUE TITLE
Plugin with id ‘maven’ not found

### ISSUE THREAD

**Issue by meycon1** [oracle/pushiomanager-react-native#54]
**What platform(s) does this occur on?**
Android

**Environment**
React-native : 0.69.1
Gradle version : 7.3.3
Project : Typescript

buildToolsVersion = "30.0.0"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30

Reproducible demo or steps to reproduce from a blank project.

![image](https://user-images.githubusercontent.com/88681908/178507842-fa342a32-30ee-4114-a7db-d9c2634061b9.png)

I think with the new gradle it is necessary to use maven-publish instead of maven

**Update the plugin:**
**So, instead of using:**
apply plugin: 'maven'
**you should use**
apply plugin: 'maven-publish'

**Comment by giovanijfc** [comment]
Hello, I apologize for my google translator english.

I had this problem and 2 hours ago they released a fix with the addition of compatibility to version 7.x.x of gradle.

oracle/pushiomanager-react-native v6.52.2

![image](https://user-images.githubusercontent.com/44476013/181099774-bf462e1d-696a-4517-91e1-f76769093293.png)

**Comment by meycon1** [comment]
Fixed: [6.52.2](https://github.com/oracle/pushiomanager-react-native/releases/tag/6.52.2)
