### ISSUE TITLE
PushIOManager.registerApp do not return error or success

### ISSUE THREAD

**Issue by cuongtran3001** [oracle/pushiomanager-react-native#6]
Hi Support,
I have configured the pushio_config successfully, but when registerapp, nothing happen(no console.log print). Could you please let me know what is the reason?

PushIOManager.configure("pushio_config.json", (error, response) => {
 console.log('configured');

 if (Platform.OS === 'android') {
    PushIOManager.registerApp(true, (error, response) => {
       console.log(error, response); //this not happen
    });
 }
});

Thank

**Comment by shamilovtim** [comment]
We also have this issue but we specifically have it on the iOS registration step

**Comment by s-wasan** [comment]
@cuongtran3001  You must be running the App in Simulator.
Please verify in the Xcode/App logs you will see this error:

> [PushIOManager] -[PushIOManager didFailToRegisterForRemoteNotificationsWithError:] Failed to get device token. Error: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}

Please run the App in device. Remote Push Notifications does not support Simulator.
Reopen this issue if you are still facing same error on Device.
