### ISSUE TITLE
is there a way to use both PushIOManager.framework? arm64 and simulator?

### ISSUE THREAD

**Issue by janmeijun** [oracle/pushiomanager-react-native#63]
is there a way to use both PushIOManager.framework? arm64 and simulator?

**Comment by janmeijun** [comment]
is there a way to use both PushIOManager.framework? arm64 and simulator?

**Comment by AndriySikora** [comment]
yes, iOS simulator on arm64 processor should be possible to connect to PushIOManager.framework. 
Device token will be provided in xCode logs, so it will mean that APNS connection is established and it should be possible to test Push Notifications from Oracle Resposnys
