### ISSUE TITLE
sdk Responys  download

### ISSUE THREAD

**Issue by ChristopherGasperiGrendene** [oracle/pushiomanager-react-native#69]
I am trying to implement push notifications using the Oracle Responsys package. The documentation mentions downloading the SDK, previously named sdk-responsys-(version). However, when I access the downloads page, I only find the CX Mobile SDK. This SDK supports integrations with services like Oracle Infinity, but it still requires Responsys. So, where is the Responsys SDK?

Is it still available for React Native?

**Comment by valaypatel** [comment]
I am facing same issue. Android and iOS SDK has 7.0.0 however React Document mention 6.5x.x version only. Kindly provide us the latest guide or older SDKs.

**Comment by ChristopherGasperiGrendene** [comment]
> I am facing same issue. Android and iOS SDK has 7.0.0 however React Document mention 6.5x.x version only. Kindly provide us the latest guide or older SDKs.

Hello, we contacted Oracle support and received a link where version 6.56 is hosted (consistent with the old documentation). We did not obtain any information regarding the new SDK. Please follow the old documentation with the older version, and you will succeed.

**Comment by valaypatel** [comment]
@ChristopherGasperiGrendene  if you can share Link or their support email that will be great. I dont have login with Oracle so cant create ticket myself.

**Comment by ChristopherGasperiGrendene** [comment]
> @ChristopherGasperiGrendenese você pode compartilhar o Link ou o e-mail de suporte deles, isso será ótimo. Eu não tenho login com o Oracle, então não posso criar um ticket sozinho.  O link que recebi requer que você esteja logado no Oracle para acessar o download. Mesmo assim, é restrito a uma área acessível apenas por um administrador (eu não tenho mais acesso). Você precisará entrar em contato com o suporte através da Oracle Community ou enviando uma Solicitação de Serviço (SR) para a Oracle.

To use PushIO, you will need access to the Responsys platform. So ensure you have the necessary access to Oracle services."
