### ISSUE TITLE
Latest release is 5 major versions behind com.google.firebase:firebase-messaging

### ISSUE THREAD

**Issue by shamilovtim** [oracle/pushiomanager-react-native#8]
Hello! We are a customer. Could you please update your project to work with a recent release of Firebase? Thank you.

<img width="1140" alt="Screen Shot 2021-05-26 at 9 52 36 AM" src="https://user-images.githubusercontent.com/3495974/119672376-8c6e8080-be08-11eb-8b0b-94235c925150.png">

**Comment by shamilovtim** [comment]
@s-wasan
@neerhaj

**Comment by neerhaj** [comment]
@shamilovtim 

Is there a build or runtime error due to this dependency?
 
The dependency is listed as `compileOnly`, so this version does not get included in your app. You can choose to include any version later than 17.3.0 in your `app/build.gradle` and it should work fine.

**Comment by shamilovtim** [comment]
Hey, thanks for the response! No there are no compile time errors. Curious though, If it doesn't change anything, why choose a version 5 major versions behind and also call for us to include that version as a peer dependency in your docs?

**Comment by shamilovtim** [comment]
@neerhaj [in the Android SDK docs](https://docs.oracle.com/en/cloud/saas/marketing/responsys-develop-mobile/android/step-by-step.htm) you can see where you call for the outdated peer dependency to be installed. thus I would say rather than validating peer dependency version on the user you guys should probably make a new release where you've validated that the peer dependency works with your package which AFAIK is how it's typically done

**Comment by shamilovtim** [comment]
I was actually too generous here. Your SDK itself (PushIOManager not pushiomanager-react-native) is **over 12 major versions behind the Firebase BoM**. You're calling for Firebase Messaging 17.3.4 which is older than even the oldest BoM that we are able to specify from Firebase. There is no way to insert a dependency this old into a modern mobile app without it breaking either its parent app or other peer dependencies. Please update your SDK and your wrapper as soon as possible. If you aren't able to resolve this issue very soon there is no way we can use Responsys within our project and we will be forced to migrate to a different product. 
<img width="462" alt="Screen Shot 2021-05-29 at 12 30 00 PM" src="https://user-images.githubusercontent.com/3495974/120077839-5a645500-c07a-11eb-9136-8b51ade6e8ee.png">

**Comment by shamilovtim** [comment]
I've also [attached a link](https://docs.oracle.com/en/cloud/saas/marketing/responsys-develop-mobile/android/step-by-step.htm) to where you specify messaging 17.3.4 as a peer dependency of pushiomanager
<img width="1601" alt="Screen Shot 2021-05-29 at 12 36 44 PM" src="https://user-images.githubusercontent.com/3495974/120077881-a31c0e00-c07a-11eb-9b90-ea779c8a3aa3.png">

**Comment by neerhaj** [comment]
Thanks for reporting this. We will have the documentation updated to reflect the most recent version of `firebase-messaging`

**Comment by shamilovtim** [comment]
> Thanks for reporting this. We will have the documentation updated to reflect the most recent version of `firebase-messaging`

Your SDK does not work with it

**Comment by neerhaj** [comment]
We are unable to address issues related to the SDK here. For SDK related issues, please raise a support request at https://support.oracle.com/. You may also contact your Oracle CX representative for help with raising the request.
